name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}-pr-${increment}"
      id: version
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"
        echo "New version: $NEW_VERSION created: $(date +%d/%m/%Y)"
        
    - name: Build Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t rvh2776/docker-graphql:$NEW_VERSION created: $(date +%d/%m/%Y) .
        docker build -t rvh2776/docker-graphql:latest .
        
    - name: Push Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push rvh2776/docker-graphql:$NEW_VERSION created: $(date +%d/%m/%Y)
        docker push rvh2776/docker-graphql:latest
        

#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
